name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simplebank_db
          POSTGRES_USER: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
        id: go
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate
      - name: Create app.env
        run: cp app.env.example app.env
      - name: Run migrations
        run: make migrateup DB_URL="postgresql://root:secret@localhost:5432/simplebank_db?sslmode=disable"
      - name: Test
        run: make test
